version: "2"

default: standard


linters:
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*).Close
        - fmt.Fprintf
        - fmt.Fprintln
        - (*github.com/hobeone/rss2go/internal/db/sqlite.Store).Close
        - rows.Close
