[mail]
sendmail = true
smtp = false
mtaPath = "sendmail"
fromAddress = "rss2go@example.net"
smtpServer = "mail.gmail.com"
smtpUsername = "example_user@gmail.com"
smtpPassword = "example_password"

[crawl]
maxCrawlers = 10
minInterval = 300
maxInterval = 3600

[db]
path = "/path/to/rss2go.db"
verbose = false
UpdateDb = true
