[mail]
sendmail = true
smtp = false
from_address = "rss2go@example.net"
to_address = "example@gmail.com"
smtp_server = "mail.gmail.com"
smtp_username = "example_user@gmail.com"
smtp_password = "example_password"

[crawl]
maxCrawlers = 10
minInterval = 300
maxInterval = 3600

[db]
path = "foo.db"
