services:
  rss2go-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    image: rss2go:latest
    container_name: rss2go-daemon
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./rss2go_docker.yaml:/app/rss2go.yaml
      - ./rss2go.db:/app/rss2go.db
    command: ["rss2go", "--config", "/app/rss2go.yaml"]
    ports:
      - "127.0.0.1:8080:8080"
